import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Archive, ArrowLeft, Bell, Building2, Check, ChevronRight, CircleUserRound, CreditCard, Database, FileCheck2, FileText, Globe2, HardDrive, KeyRound, LayoutGrid, Mail, Package, Palette, Plus, Save, Search, Settings2, ShieldCheck, ShoppingCart, Smartphone, Store, Tags, Trash2, Users, WalletCards, X } from 'lucide-react';
import { useListBranches, useListCustomers } from '@workspace/api-client-react';

type Section = { id: string; label: string; group: string; icon: typeof Settings2; description: string };
type SettingsState = { businessName: string; businessType: string; phone: string; email: string; website: string; address: string; city: string; country: string; taxNumber: string; receiptFooter: string; taxRate: string; taxName: string; currency: string; timezone: string; dateFormat: string; theme: string; defaultLocation: string; reorderLevel: string; lowStockAlerts: boolean; preventNegative: boolean; trackSize: boolean; trackLocation: boolean; requireAdjustmentReason: boolean; allowDiscounts: boolean; maxCashierDiscount: string; managerApprovalRefunds: boolean; managerApprovalDiscounts: boolean; autoReceipt: boolean; requireCustomer: boolean; allowPriceOverride: boolean; invoiceFormat: string; sessionTimeout: string; managerPin: boolean; paymentTimeout: string };
const storageKey = 'pajoy-settings';
const defaultSettings: SettingsState = { businessName: 'Pajoy Uniforms', businessType: 'School Uniform Retail & Manufacturing', phone: '+254 712 400 118', email: 'hello@pajoy.co.ke', website: 'www.pajoy.co.ke', address: 'Moi Avenue', city: 'Nairobi', country: 'Kenya', taxNumber: '', receiptFooter: 'Thank you for shopping with us.', taxRate: '16', taxName: 'VAT', currency: 'KSh', timezone: 'Africa/Nairobi', dateFormat: 'DD/MM/YYYY', theme: 'Light', defaultLocation: 'Main Warehouse', reorderLevel: '10', lowStockAlerts: true, preventNegative: true, trackSize: true, trackLocation: true, requireAdjustmentReason: true, allowDiscounts: true, maxCashierDiscount: '5', managerApprovalRefunds: true, managerApprovalDiscounts: true, autoReceipt: true, requireCustomer: false, allowPriceOverride: false, invoiceFormat: 'INV-{YYYY}-{####}', sessionTimeout: '30', managerPin: true, paymentTimeout: '60' };
const groups = [
  { name: 'Business', icon: Building2, items: [['business', 'Business Profile'], ['branches', 'Branches & Locations'], ['hours', 'Operating Hours']] },
  { name: 'Sales', icon: ShoppingCart, items: [['sales', 'Sales Settings'], ['taxes', 'Taxes'], ['discounts', 'Discounts'], ['receipts', 'Receipts']] },
  { name: 'Inventory', icon: Package, items: [['inventory', 'Inventory Settings'], ['categories', 'Categories'], ['sizes', 'Sizes'], ['units', 'Units'], ['stock-rules', 'Stock Rules']] },
  { name: 'Schools', icon: Store, items: [['schools', 'Schools'], ['requirements', 'Uniform Requirements']] },
  { name: 'Purchasing', icon: Archive, items: [['suppliers', 'Suppliers'], ['purchasing', 'Purchase Settings']] },
  { name: 'Payments', icon: CreditCard, items: [['payments', 'Payment Methods'], ['mpesa', 'M-Pesa'], ['cards', 'Card Payments']] },
  { name: 'Users & Security', icon: ShieldCheck, items: [['users', 'Users'], ['roles', 'Roles & Permissions'], ['security', 'Security'], ['audit', 'Audit Log']] },
  { name: 'Notifications', icon: Bell, items: [['notifications', 'Notifications'], ['email', 'Email'], ['sms', 'SMS']] },
  { name: 'System', icon: Settings2, items: [['general', 'General'], ['appearance', 'Appearance'], ['backup', 'Backup & Data'], ['system', 'System Information']] },
] as const;
const sections: Section[] = groups.flatMap((group) => group.items.map(([id, label]) => ({ id, label, group: group.name, icon: group.icon, description: `${label} configuration for Pajoy Uniforms.` })));
const readSettings = (): SettingsState => { try { return { ...defaultSettings, ...JSON.parse(localStorage.getItem(storageKey) ?? '{}') }; } catch { return defaultSettings; } };
function Panel({ children, className = '' }: { children: ReactNode; className?: string }) { return <section className={`rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] shadow-[var(--shadow-xs)] ${className}`}>{children}</section>; }
function Field({ label, value, onChange, type = 'text', placeholder = '' }: { label: string; value: string; onChange: (value: string) => void; type?: string; placeholder?: string }) { return <label className="block"><span className="mb-1.5 block text-[11px] font-bold text-[hsl(var(--muted-foreground))]">{label}</span><input type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="h-10 w-full rounded-lg border border-[hsl(var(--input))] bg-[hsl(var(--background))] px-3 text-sm outline-none focus:border-[hsl(var(--secondary))]" /></label>; }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <label className="block"><span className="mb-1.5 block text-[11px] font-bold text-[hsl(var(--muted-foreground))]">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="h-10 w-full rounded-lg border border-[hsl(var(--input))] bg-[hsl(var(--background))] px-3 text-sm outline-none">{options.map((option) => <option key={option}>{option}</option>)}</select></label>; }
function Toggle({ label, detail, value, onChange, danger = false }: { label: string; detail: string; value: boolean; onChange: (value: boolean) => void; danger?: boolean }) { return <label className={`flex cursor-pointer items-center justify-between gap-4 rounded-lg border p-3 ${danger ? 'border-[hsl(var(--destructive)/.3)]' : 'border-[hsl(var(--border))]'}`}><span><span className="block text-xs font-bold">{label}</span><span className="mt-1 block text-[10px] text-[hsl(var(--muted-foreground))]">{detail}</span></span><input type="checkbox" checked={value} onChange={(event) => onChange(event.target.checked)} className="h-4 w-4 accent-[hsl(var(--secondary))]" /></label>; }
function SaveBar({ onSave, saved }: { onSave: () => void; saved: boolean }) { return <div className="mt-6 flex items-center justify-between border-t border-[hsl(var(--border))] pt-4"><span className="text-xs text-[hsl(var(--muted-foreground))]">Changes are saved to this workspace.</span><button onClick={onSave} className="inline-flex items-center gap-2 rounded-lg bg-[hsl(var(--primary))] px-4 py-2.5 text-xs font-bold text-[hsl(var(--primary-foreground))]">{saved ? <Check size={14} /> : <Save size={14} />}{saved ? 'Settings saved' : 'Save changes'}</button></div>; }
function SectionHeader({ title, description, icon: Icon }: { title: string; description: string; icon: typeof Settings2 }) { return <div className="mb-5 flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[hsl(var(--secondary)/.12)] text-[hsl(var(--secondary))]"><Icon size={19} /></div><div><h2 className="font-display text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">{description}</p></div></div>; }
function ListManager({ title, items, addLabel = 'Add item', onAdd }: { title: string; items: string[]; addLabel?: string; onAdd: (value: string) => void }) { const [value, setValue] = useState(''); return <Panel className="p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-display text-base font-bold">{title}</h3><span className="text-xs text-[hsl(var(--muted-foreground))]">{items.length} configured</span></div><div className="divide-y divide-[hsl(var(--border))]">{items.map((item) => <div key={item} className="flex items-center justify-between py-3 text-sm"><span>{item}</span><button aria-label={`Remove ${item}`} className="rounded p-1 text-[hsl(var(--muted-foreground))] hover:text-[hsl(var(--destructive))]"><Trash2 size={14} /></button></div>)}</div><div className="mt-4 flex gap-2"><input value={value} onChange={(event) => setValue(event.target.value)} placeholder={addLabel} className="h-10 min-w-0 flex-1 rounded-lg border bg-[hsl(var(--background))] px-3 text-sm" /><button onClick={() => { if (value.trim()) { onAdd(value.trim()); setValue(''); } }} className="inline-flex items-center gap-2 rounded-lg border px-3 text-xs font-bold"><Plus size={14} />Add</button></div></Panel>; }
function Overview({ onSelect }: { onSelect: (id: string) => void }) { return <><div className="mb-6"><h2 className="font-display text-xl font-bold">Settings overview</h2><p className="mt-1 text-sm text-[hsl(var(--muted-foreground))]">Manage your business, POS, inventory and system configuration.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{groups.map((group) => { const Icon = group.icon; return <button key={group.name} onClick={() => onSelect(group.items[0][0])} className="group rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 text-left shadow-[var(--shadow-xs)] transition hover:-translate-y-0.5 hover:border-[hsl(var(--secondary)/.6)]"><div className="flex items-center justify-between"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[hsl(var(--secondary)/.12)] text-[hsl(var(--secondary))]"><Icon size={19} /></div><ChevronRight size={17} className="text-[hsl(var(--muted-foreground))] transition group-hover:translate-x-1" /></div><h3 className="mt-4 font-display text-base font-bold">{group.name}</h3><p className="mt-1 text-xs leading-5 text-[hsl(var(--muted-foreground))]">{group.name === 'Business' ? 'Manage company information and locations.' : group.name === 'Sales' ? 'Configure POS, receipts, taxes and discounts.' : group.name === 'Inventory' ? 'Configure stock rules, sizes and categories.' : group.name === 'Schools' ? 'Manage schools and uniform requirements.' : group.name === 'Payments' ? 'Configure accepted payment methods.' : group.name === 'Users & Security' ? 'Manage staff accounts and permissions.' : group.name === 'Notifications' ? 'Configure SMS, email and system alerts.' : 'Manage general preferences and backups.'}</p><div className="mt-3 text-[10px] font-bold uppercase tracking-[.12em] text-[hsl(var(--secondary))]">{group.items.length} sections</div></button>; })}</div></>; }
function FormSection({ id, settings, update, onSave, saved, listItems, setListItems }: { id: string; settings: SettingsState; update: (key: keyof SettingsState, value: string | boolean) => void; onSave: () => void; saved: boolean; listItems: Record<string, string[]>; setListItems: (key: string, value: string[]) => void }) {
  const section = sections.find((item) => item.id === id) ?? sections[0]; const common = (children: ReactNode) => <><SectionHeader title={section.label} description={section.description} icon={section.icon} /><Panel className="p-5">{children}<SaveBar onSave={onSave} saved={saved} /></Panel></>;
  if (id === 'business') return common(<div className="grid gap-4 sm:grid-cols-2"><Field label="Business name" value={settings.businessName} onChange={(value) => update('businessName', value)} /><Field label="Business type" value={settings.businessType} onChange={(value) => update('businessType', value)} /><Field label="Phone" value={settings.phone} onChange={(value) => update('phone', value)} /><Field label="Email" value={settings.email} onChange={(value) => update('email', value)} /><Field label="Website" value={settings.website} onChange={(value) => update('website', value)} /><Field label="Address" value={settings.address} onChange={(value) => update('address', value)} /><Field label="City" value={settings.city} onChange={(value) => update('city', value)} /><Field label="Country" value={settings.country} onChange={(value) => update('country', value)} /><Field label="Tax/VAT registration number" value={settings.taxNumber} onChange={(value) => update('taxNumber', value)} /><label className="block sm:col-span-2"><span className="mb-1.5 block text-[11px] font-bold text-[hsl(var(--muted-foreground))]">Logo</span><input type="file" accept="image/*" className="block h-10 w-full rounded-lg border bg-[hsl(var(--background))] px-2 py-2 text-xs" /></label></div>);
  if (id === 'sales') return common(<div className="space-y-3"><Field label="Invoice/receipt number format" value={settings.invoiceFormat} onChange={(value) => update('invoiceFormat', value)} /><div className="rounded-lg bg-[hsl(var(--muted)/.5)] p-3 text-xs">Preview: <strong>INV-2026-004582</strong></div><Toggle label="Automatically generate receipt" detail="Create a receipt after completed payment." value={settings.autoReceipt} onChange={(value) => update('autoReceipt', value)} /><Toggle label="Require customer for sale" detail="Ask for customer details before completing a sale." value={settings.requireCustomer} onChange={(value) => update('requireCustomer', value)} /><Toggle label="Allow price override" detail="Limit overrides to authorized staff." value={settings.allowPriceOverride} onChange={(value) => update('allowPriceOverride', value)} /><Toggle label="Allow negative inventory" detail="Not recommended for uniform stock control." value={false} onChange={() => undefined} danger /></div>);
  if (id === 'taxes') return common(<div className="grid gap-4 sm:grid-cols-2"><Toggle label="Tax enabled" detail="Apply tax consistently across POS and reports." value={true} onChange={() => undefined} /><Toggle label="Prices include tax" detail="Display tax-inclusive prices at checkout." value={true} onChange={() => undefined} /><Field label="Tax name" value={settings.taxName} onChange={(value) => update('taxName', value)} /><Field label="Default tax rate (%)" type="number" value={settings.taxRate} onChange={(value) => update('taxRate', value)} /><div className="sm:col-span-2 rounded-lg border p-4 text-sm"><div className="flex justify-between py-2"><span>VAT</span><strong>{settings.taxRate}%</strong></div><div className="flex justify-between border-t py-2"><span>Zero rated</span><strong>0%</strong></div><div className="flex justify-between border-t py-2"><span>Exempt</span><strong>0%</strong></div></div></div>);
  if (id === 'discounts') return common(<div className="space-y-3"><Toggle label="Allow discounts" detail="Enable discount controls at the POS." value={settings.allowDiscounts} onChange={(value) => update('allowDiscounts', value)} /><Field label="Maximum cashier discount (%)" type="number" value={settings.maxCashierDiscount} onChange={(value) => update('maxCashierDiscount', value)} /><Toggle label="Manager approval required" detail="Discounts above the cashier limit require approval." value={settings.managerApprovalDiscounts} onChange={(value) => update('managerApprovalDiscounts', value)} /><Toggle label="Require discount reason" detail="Record a reason in the audit trail." value={true} onChange={() => undefined} /></div>);
  if (id === 'receipts') return common(<div className="grid gap-4 sm:grid-cols-2"><Field label="Receipt business name" value={settings.businessName} onChange={(value) => update('businessName', value)} /><Field label="Receipt phone" value={settings.phone} onChange={(value) => update('phone', value)} /><Field label="Receipt email" value={settings.email} onChange={(value) => update('email', value)} /><Field label="Receipt address" value={settings.address} onChange={(value) => update('address', value)} /><Field label="Footer message" value={settings.receiptFooter} onChange={(value) => update('receiptFooter', value)} /><div className="rounded-lg border p-3 text-xs"><strong>Included fields</strong><p className="mt-2 leading-6 text-[hsl(var(--muted-foreground))]">Receipt number, date, cashier, register, customer, school, items, sizes, quantity, price, discount, tax, total and payment method.</p></div></div>);
  if (id === 'inventory' || id === 'stock-rules') return common(<div className="space-y-3"><SelectField label="Default stock location" value={settings.defaultLocation} options={['Main Warehouse', 'Westlands Branch', 'Nairobi Branch', 'School Outlet']} onChange={(value) => update('defaultLocation', value)} /><Field label="Default reorder level" type="number" value={settings.reorderLevel} onChange={(value) => update('reorderLevel', value)} /><Toggle label="Low stock alerts" detail="Notify staff when inventory reaches its reorder level." value={settings.lowStockAlerts} onChange={(value) => update('lowStockAlerts', value)} /><Toggle label="Prevent negative stock" detail="Block sales that exceed available stock." value={settings.preventNegative} onChange={(value) => update('preventNegative', value)} /><Toggle label="Track stock by size" detail="Keep each uniform size as a separate stock record." value={settings.trackSize} onChange={(value) => update('trackSize', value)} /><Toggle label="Track stock by location" detail="Separate warehouse and branch quantities." value={settings.trackLocation} onChange={(value) => update('trackLocation', value)} /><Toggle label="Require stock adjustment reason" detail="Record an audit reason for every adjustment." value={settings.requireAdjustmentReason} onChange={(value) => update('requireAdjustmentReason', value)} /></div>);
  if (['categories', 'sizes', 'units'].includes(id)) return <><SectionHeader title={section.label} description={section.description} icon={section.icon} /><ListManager title={section.label} items={listItems[id]} onAdd={(value) => setListItems(id, [...listItems[id], value])} /></>;
  if (id === 'branches') return <><SectionHeader title="Branches & Locations" description="Manage warehouses, branches, and school outlets." icon={Building2} /><ListManager title="Active locations" items={listItems.branches} addLabel="Location name" onAdd={(value) => setListItems('branches', [...listItems.branches, value])} /></>;
  if (id === 'hours') return common(<div className="space-y-2">{['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].map((day, index) => <div key={day} className="grid grid-cols-[1fr_auto_auto_auto] items-center gap-2 rounded-lg border p-3 text-xs"><strong>{day}</strong><input type="time" defaultValue={index === 5 ? '09:00' : '08:00'} className="h-9 rounded border bg-transparent px-2" /><span>to</span><input type="time" defaultValue={index === 5 ? '16:00' : index === 6 ? '00:00' : '18:00'} className="h-9 rounded border bg-transparent px-2" /></div>)}</div>);
  if (id === 'schools' || id === 'suppliers' || id === 'users') return <><SectionHeader title={section.label} description={section.description} icon={section.icon} /><ListManager title={section.label} items={listItems[id]} addLabel={`Add ${section.label.toLowerCase().replace(/s$/, '')}`} onAdd={(value) => setListItems(id, [...listItems[id], value])} /></>;
  if (id === 'requirements') return common(<div className="space-y-3"><SelectField label="School" value="Greenfield Academy" options={['Greenfield Academy', 'Westlands Academy', 'Nairobi Academy', "St. Mary's School"]} onChange={() => undefined} /><div className="rounded-lg border p-4"><div className="mb-3 text-xs font-bold">Boys - Primary requirements</div>{['White Shirt', 'Grey Trouser', 'Blue Sweater', 'School Tie', 'Black Socks', 'Sports Kit'].map((item) => <label key={item} className="flex items-center gap-2 border-t py-2 text-sm"><input type="checkbox" defaultChecked />{item}<span className="ml-auto text-[10px] text-[hsl(var(--muted-foreground))]">Qty 1</span></label>)}</div></div>);
  if (id === 'payments') return common(<div className="space-y-2">{['Cash', 'M-Pesa', 'Card', 'Bank Transfer', 'Other'].map((method, index) => <div key={method} className="flex items-center justify-between rounded-lg border p-3 text-sm"><span className="font-bold">{method}</span><div className="flex items-center gap-3"><span className="text-xs text-[hsl(var(--muted-foreground))]">{index === 4 ? 'Disabled' : 'Enabled'}</span><input type="checkbox" defaultChecked={index !== 4} /></div></div>)}</div>);
  if (id === 'mpesa' || id === 'cards') return common(<div className="space-y-3"><Toggle label={`Enable ${id === 'mpesa' ? 'M-Pesa' : 'card payments'}`} detail="Credentials remain on the server and are never displayed here." value={true} onChange={() => undefined} /><SelectField label="Environment" value="Sandbox" options={['Sandbox', 'Production']} onChange={() => undefined} /><Field label={id === 'mpesa' ? 'Till / Paybill number' : 'Provider'} value={id === 'mpesa' ? '174379' : 'Terminal provider'} onChange={() => undefined} /><Field label="Payment timeout (seconds)" type="number" value={settings.paymentTimeout} onChange={(value) => update('paymentTimeout', value)} /><div className="rounded-lg bg-[hsl(145_35%_88%)] p-3 text-xs font-semibold text-[hsl(145_37%_30%)]">Connection status: Connected. Secrets are masked.</div></div>);
  if (id === 'roles' || id === 'security') return common(<div className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-lg border p-4"><div className="font-bold">Cashier</div><div className="mt-2 text-xs text-[hsl(var(--muted-foreground))]">Sales, payments, own reports. No costs or stock changes.</div></div><div className="rounded-lg border p-4"><div className="font-bold">Inventory staff</div><div className="mt-2 text-xs text-[hsl(var(--muted-foreground))]">Receive, transfer, count and permitted adjustments.</div></div><div className="rounded-lg border p-4"><div className="font-bold">Manager</div><div className="mt-2 text-xs text-[hsl(var(--muted-foreground))]">Reports, approvals, inventory and orders.</div></div><div className="rounded-lg border p-4"><div className="font-bold">Admin / Owner</div><div className="mt-2 text-xs text-[hsl(var(--muted-foreground))]">Full configuration and financial access.</div></div></div><Field label="Session timeout (minutes)" type="number" value={settings.sessionTimeout} onChange={(value) => update('sessionTimeout', value)} /><Toggle label="Require manager PIN" detail="Protect refunds, price overrides, and sensitive actions." value={settings.managerPin} onChange={(value) => update('managerPin', value)} /></div>);
  if (id === 'audit') return common(<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead className="border-b text-[10px] uppercase tracking-[.1em] text-[hsl(var(--muted-foreground))]"><tr><th className="py-3">Date/time</th><th>User</th><th>Action</th><th>Module</th><th>Description</th></tr></thead><tbody className="divide-y"><tr><td className="py-3">Sep 4, 08:40</td><td>David</td><td>Adjustment</td><td>Inventory</td><td>White Shirt -2</td></tr><tr><td className="py-3">Sep 4, 09:05</td><td>Sarah</td><td>Refund</td><td>Sales</td><td>REF-00042 approved</td></tr></tbody></table></div>);
  if (id === 'notifications' || id === 'email' || id === 'sms') return common(<div className="space-y-3">{['Low stock alerts', 'Out-of-stock alerts', 'Refund alerts', 'Failed payment alerts', 'Daily sales summary', 'End-of-day report'].map((item) => <Toggle key={item} label={item} detail="Choose delivery channels after enabling this alert." value={true} onChange={() => undefined} />)}{(id === 'email' || id === 'sms') && <div className="grid gap-3 pt-2 sm:grid-cols-2"><Field label={id === 'email' ? 'Sender email' : 'Sender ID'} value={id === 'email' ? settings.email : 'PAJOY'} onChange={() => undefined} /><SelectField label="Connection status" value="Connected" options={['Connected', 'Not connected']} onChange={() => undefined} /></div>}</div>);
  if (id === 'appearance' || id === 'general') return common(<div className="grid gap-4 sm:grid-cols-2"><SelectField label="Theme" value={settings.theme} options={['Light', 'Dark', 'System']} onChange={(value) => update('theme', value)} /><SelectField label="Currency" value={settings.currency} options={['KSh', 'USD', 'EUR']} onChange={(value) => update('currency', value)} /><SelectField label="Timezone" value={settings.timezone} options={['Africa/Nairobi', 'UTC']} onChange={(value) => update('timezone', value)} /><SelectField label="Date format" value={settings.dateFormat} options={['DD/MM/YYYY', 'MM/DD/YYYY', 'YYYY-MM-DD']} onChange={(value) => update('dateFormat', value)} /><SelectField label="Sidebar" value="Expanded" options={['Expanded', 'Compact']} onChange={() => undefined} /></div>);
  if (id === 'backup') return common(<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-lg bg-[hsl(var(--muted)/.5)] p-3"><div className="text-[10px] uppercase text-[hsl(var(--muted-foreground))]">Last backup</div><strong className="mt-1 block text-sm">Sep 3, 2026</strong></div><div className="rounded-lg bg-[hsl(var(--muted)/.5)] p-3"><div className="text-[10px] uppercase text-[hsl(var(--muted-foreground))]">Status</div><strong className="mt-1 block text-sm text-[hsl(145_37%_30%)]">Healthy</strong></div><div className="rounded-lg bg-[hsl(var(--muted)/.5)] p-3"><div className="text-[10px] uppercase text-[hsl(var(--muted-foreground))]">Database size</div><strong className="mt-1 block text-sm">18.4 MB</strong></div></div><div className="flex flex-wrap gap-2"><button onClick={() => window.alert('Backup queued successfully.')} className="inline-flex items-center gap-2 rounded-lg bg-[hsl(var(--primary))] px-3 py-2.5 text-xs font-bold text-[hsl(var(--primary-foreground))]"><HardDrive size={14} />Backup now</button><button onClick={() => window.alert('Restore requires administrator confirmation.')} className="inline-flex items-center gap-2 rounded-lg border border-[hsl(var(--destructive)/.4)] px-3 py-2.5 text-xs font-bold text-[hsl(var(--destructive))]">Restore backup</button></div></div>);
  if (id === 'system') return common(<div className="grid gap-3 sm:grid-cols-2">{[['Application', 'School Uniform POS'], ['Version', '1.0.0'], ['Database', 'Unavailable - demo mode'], ['API', 'Unavailable - demo mode'], ['Environment', 'Development'], ['Support', 'support@pajoy.co.ke']].map(([label, value]) => <div key={label} className="rounded-lg bg-[hsl(var(--muted)/.5)] p-4"><div className="text-[10px] uppercase tracking-[.1em] text-[hsl(var(--muted-foreground))]">{label}</div><div className="mt-1 text-sm font-bold">{value}</div></div>)}</div>);
  return common(<div className="grid gap-3 sm:grid-cols-2"><Toggle label="Enable feature" detail="This setting is ready for server-backed configuration." value={true} onChange={() => undefined} /><Field label="Configuration value" value="Configured" onChange={() => undefined} /></div>);
}

export default function SettingsModule() { 
  const [active, setActive] = useState('overview'); 
  const [search, setSearch] = useState(''); 
  const [settings, setSettings] = useState<SettingsState>(readSettings); 
  const [saved, setSaved] = useState(false);
  
  // Fetch real data from API
  const { data: branches = [] } = useListBranches({ query: { queryKey: ['branches'] } });
  const { data: customers = [] } = useListCustomers({ query: { queryKey: ['customers'] } });
  
  // Extract schools from customers (customers with type="School")
  const schools = useMemo(() => 
    customers.filter(c => c.type === 'School').map(c => c.name),
    [customers]
  );
  
  // Extract branch names from API
  const branchNames = useMemo(() => 
    branches.map(b => b.name),
    [branches]
  );
  
  const [listItems, setListItemsState] = useState<Record<string, string[]>>({ 
    categories: ['Shirts', 'Trousers', 'Sweaters', 'Sportswear'], 
    sizes: ['4', '6', '8', '10', '12', '14', '16', '18', 'XS', 'S', 'M', 'L', 'XL', 'XXL'], 
    units: ['Piece', 'Pair', 'Set', 'Dozen'], 
    branches: branchNames.length > 0 ? branchNames : ['Main Warehouse', 'Westlands Branch', 'Nairobi Branch', 'School Outlet'], 
    schools: schools.length > 0 ? schools : ['Greenfield Academy', 'Westlands Academy', 'Nairobi Academy', "St. Mary's School"], 
    suppliers: ['ABC Uniform Suppliers', 'Nairobi Textiles', 'Schoolwear Kenya'], 
    users: ['Jane Kamau - Cashier', 'David Otieno - Inventory', 'Sarah Wanjiku - Manager'] 
  });
  
  // Update list items when API data changes
  useEffect(() => {
    if (branchNames.length > 0) {
      setListItemsState(prev => ({ ...prev, branches: branchNames }));
    }
  }, [branchNames]);
  
  useEffect(() => {
    if (schools.length > 0) {
      setListItemsState(prev => ({ ...prev, schools }));
    }
  }, [schools]);
  
  const filteredSections = useMemo(() => sections.filter((section) => !search || `${section.label} ${section.group}`.toLowerCase().includes(search.toLowerCase())), [search]); 
  const update = (key: keyof SettingsState, value: string | boolean) => setSettings((current) => ({ ...current, [key]: value })); 
  const save = () => { localStorage.setItem(storageKey, JSON.stringify(settings)); setSaved(true); window.setTimeout(() => setSaved(false), 1800); }; 
  const setListItems = (key: string, value: string[]) => setListItemsState((current) => ({ ...current, [key]: value })); 
  const activeSection = sections.find((section) => section.id === active); 
  return <div><div className="mb-7"><div className="mb-2 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-[hsl(var(--secondary))]"><span className="h-1.5 w-1.5 rounded-full bg-[hsl(var(--accent))]" />Control room</div><h1 className="font-display text-3xl font-bold tracking-[-.045em]">Settings</h1><p className="mt-1.5 max-w-xl text-sm text-[hsl(var(--muted-foreground))]">Manage your business, POS, inventory and system configuration.</p></div><div className="grid gap-5 lg:grid-cols-[260px_minmax(0,1fr)]"><Panel className="h-fit overflow-hidden"><div className="border-b border-[hsl(var(--border))] p-4"><div className="relative"><Search size={14} className="absolute left-3 top-3 text-[hsl(var(--muted-foreground))]" /><input aria-label="Search settings" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search settings..." className="h-10 w-full rounded-lg border bg-[hsl(var(--background))] pl-9 pr-3 text-xs outline-none focus:border-[hsl(var(--secondary))]" /></div></div><div className="max-h-[70vh] overflow-y-auto p-2"><button onClick={() => setActive('overview')} className={`mb-2 flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-left text-xs font-bold ${active === 'overview' ? 'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]' : 'hover:bg-[hsl(var(--muted))]'}`}><LayoutGrid size={15} />Overview</button>{groups.map((group) => { const visible = group.items.filter(([id, label]) => filteredSections.some((section) => section.id === id || section.label === label)); if (!visible.length) return null; const Icon = group.icon; return <div key={group.name} className="mb-3"><div className="flex items-center gap-2 px-3 py-2 text-[10px] font-bold uppercase tracking-[.13em] text-[hsl(var(--muted-foreground))]"><Icon size={13} />{group.name}</div>{visible.map(([id, label]) => <button key={id} onClick={() => setActive(id)} className={`flex w-full items-center justify-between rounded-lg px-3 py-2 text-left text-xs font-semibold ${active === id ? 'bg-[hsl(var(--secondary)/.12)] text-[hsl(var(--secondary))]' : 'hover:bg-[hsl(var(--muted))]'}`}><span>{label}</span>{active === id && <ChevronRight size={13} />}</button>)}</div>; })}</div></Panel><main className="min-w-0">{active === 'overview' ? <Overview onSelect={setActive} /> : activeSection ? <FormSection id={active} settings={settings} update={update} onSave={save} saved={saved} listItems={listItems} setListItems={setListItems} /> : null}<div className="mt-5 flex items-center gap-2 text-[10px] text-[hsl(var(--muted-foreground))]"><ShieldCheck size={13} />Sensitive settings are intended for authorized managers and administrators. Backend authorization remains required for production enforcement.</div></main></div></div>; }
